[http_service]
  internal_port = 8080 # Cổng nội bộ mà ứng dụng của bạn lắng nghe
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1

  [[http_service.rules]]
    match = "path_prefix"
    regex = "^/abc/?$"
    rewrite_path = "/index.htm" # Đường dẫn nội bộ mà request sẽ được rewrite tới
